### ISSUE TITLE
ESP32-audioI2S crashes on arduino-esp32 v3.0.7

### ISSUE THREAD

**Issue by enjoyneering** [schreibfaul1/ESP32-audioI2S#875] opened 2024-10-24 01:36 UTC
Hi schreibfaul1,

The latest ESP32-audioI2S v3.0.13d crashes on arduino-esp32 v3.0.7. Same code works OK on arduino-esp32 v3.0.5. I'm not an expert, but I think the problem is related to the latest changes in arduino PSRAM. The Exception Decoder points to Audio::setDefaults().

The hardware I use:
ESP32-S3 R8N2 at 240Mhz with 8MB flash at 80MHz (QIO) & 2MB PSRAM (QSPI).

![Exception_Decoder_setDefaults()](https://github.com/user-attachments/assets/7e1c388f-4a26-4f0a-9842-d02e5b68f215)

**Comment by schreibfaul1** [comment] 2024-10-24 17:18
The Arduino version 3.0.7 was released recently. I have tested this version in VSCode nit PIO and have not been able to reproduce the error. According to your log, there is a memory violation during an if query. Strange, maybe the error only occurs under certain configurations?

**Comment by enjoyneering** [comment] 2024-10-25 02:57
Hi schreibfaul1,

If I disable PSRAM, my code works fine on arduino-esp32 v3.0.7. Looks like problem is related to the latest changes in arduino PSRAM:
- https://github.com/espressif/arduino-esp32/pull/10406
- https://github.com/espressif/arduino-esp32/pull/10395
- https://github.com/espressif/arduino-esp32/pull/10390

**Comment by enjoyneering** [comment] 2024-10-26 00:59
I enabled PSRAM, commented out the line audio.connecttohost(AUDIO_WEBRADIO_00); and everything worked, without sound.

![codec_info](https://github.com/user-attachments/assets/4299fdcb-3b7d-4f4e-9360-dc1bec52792a)
![sys_info](https://github.com/user-attachments/assets/31fb63d0-1a3e-4e75-a5e2-6290eb1dc2cc)

**Comment by stef-ladefense** [comment] 2024-10-26 19:46
hi, I have exactly the same crashes with version 3.07.

I went back to version ESP32-audioI2S-3.0.12f to work with 3.07.
with 3.05, version ESP32-audioI2S-3.0.13e works.

**Comment by schreibfaul1** [comment] 2024-10-27 09:54
I have now tested V3.0.7 in the Arduino IDE. @enjoyneering is right, PSRAM is not initialised correctly. This leads to an "out of memory".
![image](https://github.com/user-attachments/assets/e41342e6-848f-4623-aaa8-ddfa116f1777)

Arduino V3.0.5 works.

**Comment by me-no-dev** [comment] 2024-10-29 11:38
The problem is not in Arduino, but in the library constructor: https://github.com/schreibfaul1/ESP32-audioI2S/blob/master/src/Audio.cpp#L161

It is allocating and dealing with memory BEFORE the memory is properly initialized. All that code should be executed in `setup()` and not before that.

It worked before, because it ran before any PSRAM was touched, thus acting like PSRAM is not there at all.

**Comment by me-no-dev** [comment] 2024-10-29 13:32
This does not change the fact that in the constructor (which runs before PSRAM is added to heap and anything else is started and prepared) there are many things done that should not be done there.  All that should happen in the constructor is basic class variables setup. All other memory operations should be done later in `setup()`. Starting I2S also.  That `oom` error above happened at the same time that PSRAM was enabled, which means that the code that allocates memory started even earlier. This all lands the constructor in no man's land (at the same time that memory map for the OS is being set).

**Comment by me-no-dev** [comment] 2024-10-29 13:36
This has not been a problem so far, because PSRAM was initialized AFTER `Audio::Audio()`, therefore PSRAM was not even on yet. You were starting it yourself [here](https://github.com/schreibfaul1/ESP32-audioI2S/blob/master/src/Audio.cpp#L171) which is also a very bad idea. This is a private API that is called by the core at the appropriate time. Please revise your constructor, else coming 3.1.0 there will be even more issues with the memory

**Comment by schreibfaul1** [comment] 2024-10-29 14:20
@me-no-dev Thanks for the explanation. The PSRAM will now be initialised at a later time, everything is perfect, and in the Arduino IDE it is now also running.
I think I can close this topic with that.

**Closed by schreibfaul1** 2024-10-29 14:20 UTC
